// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​p​p​ ​s​t​a​r​t​e​d
	 */
	startup: string
}

export type TranslationFunctions = {
	/**
	 * App started
	 */
	startup: () => LocalizedString
}

export type Formatters = {}
