name: CI - Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Run-Build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: volta-cli/action@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install pnpm by volta
              run: volta install pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build storybook
              uses: mansagroup/nrwl-nx-action@v3
              with:
                targets: build-storybook
                all: 'true'
                parallel: 3
                nxCloud: 'true'
